name: book_store
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - ./assets/covers/book1.jpeg
    - ./assets/covers/book2.jpg
    - ./assets/covers/book3.png
    - ./assets/covers/book4.jpg
    - ./assets/covers/book5.jpg
    - ./assets/covers/book6.jpg
    - ./assets/covers/book7.jpg
    - ./assets/covers/book8.webp
    - ./assets/covers/book9.jpg